---
abstract: 'A simple procedural interface do http verbs'
author:
  - 'Italo Gonçales <italo.goncales@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-Simple-REST
requires:
  HTTP::Server::Simple: 0
  JSON: 0
  Test::Exception: 0
version: 0.002
